[package]
name = "vec_operations"
version = "0.1.0"
authors = ["Neelakantan K.K. <neelakantankk@Terrapin-Station.Candyman>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
